linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    checks: ["all"]

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - predeclared

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/app/services/mocks/.*\.go
      linters:
        - errcheck
        - govet
        - staticcheck

  max-issues-per-linter: 0
  max-same-issues: 0